-- ##Title web-运营经理操作管理-品类供应管理-供应渠道成果管理-二维码-查看详情
-- ##Author 卢文彪
-- ##CreateTime 2023-09-15
-- ##Describe <p>空脚本,使用接口同:web-对接专员操作管理-购方/供方对接管理-购方用户成果管理/供方对接成果管理-二维码-查看详情(办理申请点击) Name:aprcAM\Web\DjRoleUser\OrderAccept\getDeatilQrocdeByTargetType_1_0_1</p>
-- ##CallType[QueryData]
